{{- if and .Values.global.opentdf.common.istio.enabled .Values.keycloak.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "keycloak.fullname" .Subcharts.keycloak }}-vsvc
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ ( include "backend.ingress.gateway" . ) }}
  hosts: {{ .Values.global.opentdf.common.istio.ingress.hosts | toYaml | nindent 4 }}
  http:
    - match:
        - uri:
            prefix: /auth/
        - uri:
            prefix: /auth
      name: {{ template "keycloak.fullname" .Subcharts.keycloak }}
      route:
        - destination:
            host: {{ template "keycloak.fullname" .Subcharts.keycloak }}-http
            port:
              name: http
              number: 80
{{- end -}}