abacus:
  replicaCount: 1
  image:
    repository: virtru/tdf-abacus-web
    tag: virtrulocal
    pullPolicy: Never
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: 'true'
    enabled: true
    hosts:
    - host: abacus.etheria.local
      paths:
      - backend:
          service:
            name: abacus
            port: 443
        path: /(.*)
      - backend:
          service:
            name: eas
            port: 4010
        path: /eas/(.*)
      - backend:
          service:
            name: kas
            port: 8000
        path: /kas/(.*)
    tls:
    - hosts:
      - abacus.etheria.local
      secretName: abacus-tls
  endpoints:
    eas: https://abacus.etheria.local/eas
    kas: https://abacus.etheria.local/kas
    abacus: https://abacus.etheria.local
    nginxHost: abacus.etheria.local
eas:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: abacus.etheria.local
      paths:
      - /eas
    tls:
    - hosts:
      - abacus.etheria.local
      secretName: eas-tls
  endpoints:
    kasDefaultUrl: https://abacus.etheria.local/kas
  image:
    name: virtru/tdf-entity-attribute-service:virtrulocal
    pullPolicy: Never
  service:
    type: ClusterIP

kas:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: abacus.etheria.local
      paths:
      - /kas
    tls:
    - hosts:
      - abacus.etheria.local
      secretName: kas-tls
  endpoints:
    easHost: https://abacus.etheria.local/eas
  image:
    name: virtru/tdf-key-access-service:virtrulocal
    pullPolicy: Never

attribute-provider:
  image:
    name: virtru/tdf-claim-test-webservice:virtrulocal
    pullPolicy: Never
  port: 5000

keycloak-bootstrap:
  image:
    name: virtru/tdf-keycloak-bootstrap:virtrulocal
    pullPolicy: Never

attribute-authority:
  image:
    name: virtru/tdf-attribute-authority-service:virtrulocal
    pullPolicy: Never
  postgres:
    host: my-tdfdb-postgresql.default.svc.cluster.local
    port: 5432
    user: postgres
    schema: tdf_attribute

entitlement:
  image:
    name: virtru/tdf-entitlement-service:virtrulocal
    pullPolicy: Never
  postgres:
    host: my-tdfdb-postgresql.default.svc.cluster.local
    port: 5432
    database: tdf_database
    schema: tdf_entitlement

tdf-storage:
  image:
    name: virtru/tdf-storage-service:virtrulocal
    pullPolicy: Never
  s3Bucket: "datalake.etheria"
  s3BucketRegion: "us-west-2"
