# Development image for minikube - for nonlocal envs, override this with a proper version
# This should be preloaded into minikube by a local setup script
image:
  repository: tdf3.service.keycloak
  tag: virtrulocal
  pullPolicy: Never
extraEnv: |
  - name: KEYCLOAK_USER
    value: technoking
  - name: KEYCLOAK_PASSWORD
    value: elon-musk-is-a-dork
  - name: ATTRIBUTE_PROVIDER_URL
    value: http://attribute-provider:5000
