# Development image for minikube - for nonlocal envs, override this with a proper version
# This should be preloaded into minikube by a local setup script
image:
#  ghcr.io == GitHub packages
  registry: docker.io
  repository: opentdf/keycloak
  tag: head
  pullPolicy: Never
extraEnv: |
  - name: KEYCLOAK_USER
    value: keycloakadmin
  - name: KEYCLOAK_PASSWORD
    value: mykeycloakpassword
  - name: CLAIMS_URL
    value: http://attribute-provider:5000
