definitions:
  handlers.EntitlementsRequest:
    description: Request containing entity identifiers seeking entitlement. At least
      one entity (primary requestor) is required The Entitlements PDP is expected
      to be invoked directly by an identity provider and with contextual entity information
      attested to and possessed by that identity provider
    properties:
      entitlement_context_obj:
        description: |-
          Optional, may be left empty.
          A free-form, (valid, escaped) JSON object in string format, containing any additional IdP/input context around and from
          the entity authentication process. This JSON object will be checked as a valid, generic JSON document,
          and then passed to the PDP engine as-is, as an input document.
        example: '{"somekey":"somevalue"}'
        type: string
      primary_entity_id:
        description: |-
          The identifier for the primary entity seeking entitlement.
          For PE auth, this will be a PE ID. For NPE/direct grant auth, this will be an NPE ID.
        example: bc03f40c-a7af-4507-8198-d5334e2823e6
        type: string
      secondary_entity_ids:
        description: |-
          Optional, may be left empty.
          For PE auth, this will be one or more NPE IDs (client-on-behalf-of-user).
          For NPE/direct grant auth,
          this may be either empty (client-on-behalf-of-itself) or populated with one
          or more NPE IDs (client-on-behalf-of-other-clients, aka chaining flow)
        example:
        - 4f6636ca-c60c-40d1-9f3f-015086303f74
        items:
          type: string
        type: array
    type: object
  handlers.EntityAttribute:
    description: Represents a single entity attribute.
    properties:
      attribute:
        description: 'Attribute, in URI format, e.g.: "https://example.org/attr/Classification/value/COI"'
        example: https://example.org/attr/OPA/value/AddedByOPA
        type: string
      displayName:
        description: Optional display name for the attribute
        example: Added By OPA
        type: string
    type: object
  handlers.EntityEntitlement:
    properties:
      entity_attributes:
        items:
          $ref: '#/definitions/handlers.EntityAttribute'
        type: array
      entity_identifier:
        example: bc03f40c-a7af-4507-8198-d5334e2823e6
        type: string
    type: object
info:
  contact:
    name: OpenTDF
    url: https://www.opentdf.io
  description: An implementation of a Policy Decision Point
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: entitlement-pdp
  version: 0.0.1
paths:
  /entitlements:
    post:
      consumes:
      - application/json
      description: |-
        Provide entity identifiers to the entitlement PDP
        and receive an array of attribute sets for each entity involved in the entitlement decisions
      parameters:
      - description: List of primary and secondary entity identifiers to entitle
        in: body
        name: Request"
        required: true
        schema:
          $ref: '#/definitions/handlers.EntitlementsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.EntityEntitlement'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Request an entitlements set from the PDP
      tags:
      - Entitlements
  /healthz:
    get:
      responses:
        "200":
          description: OK
        "503":
          description: Service Unavailable
          schema:
            type: string
      summary: Check service status
      tags:
      - Service Health
swagger: "2.0"
