# TODO DEPRECATED - this should be dropped in favor of a Helm-based install and KUTTL test
version: "3.8"
volumes:
  key-store:
services:
  eas:
    depends_on:
      - postgres
    environment:
      - EAS_ATTRIBUTES_JSON
      - EAS_DB_PATH=/eas_app/db/data/eas_database.sqlite
      - EAS_PRIVATE_KEY
      - EAS_CERTIFICATE
      - EAS_UID=908
      - EAS_USERS_JSON
      - FLASK_DEBUG=True
      - GUNICORN_PORT=4010
      - GUNICORN_WORKERS=1
      - JSON_LOGGER=False
      - KAS_DEFAULT_URL=https://etheria.local:4443/kas
      - KAS_EC_SECP256R1_CERTIFICATE
      - KAS_CERTIFICATE
      - LOGLEVEL=DEBUG
      - MONOLOG_LEVEL
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=eas_user
      - POSTGRES_PASSWORD=eas_password
      - POSTGRES_DB=eas_db
    expose:
      - 4010
    build:
      args:
        - PY_VERSION=${PY_VERSION:-3.9}
      context: ./containers/eas
      dockerfile: Dockerfile
    logging:
      options:
        max-file: "5"
        max-size: "10m"
  kas:
    build:
      args:
        - ALPINE_VERSION=${ALPINE_VERSION:-3.13}
        - LEGACY_NANOTDF_IV=1
        - PY_VERSION=${PY_VERSION:-3.9}
      context: ./containers/kas
      dockerfile: Dockerfile
    environment:
      - EAS_HOST=https://etheria.local/eas/
      - EAS_CERTIFICATE
      - FLASK_DEBUG=True
      - GUNICORN_WORKERS=1
      - JSON_LOGGER=False
      - KAS_EC_SECP256R1_PRIVATE_KEY
      - KAS_EC_SECP256R1_CERTIFICATE
      - KAS_PRIVATE_KEY
      - KAS_CERTIFICATE
      - CA_CERT_PATH=/certs/ca.crt
      - LOGLEVEL=DEBUG
      - MONOLOG_LEVEL
      - KAS_UID=909
    expose:
      - 8000
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
       - ./certs/ca.crt:/certs/ca.crt
  etheria.local:
    depends_on:
      - eas
      - kas
    entrypoint:
      - "/entrypoint.sh"
    environment:
      - EAS_URL=http://eas:4010
      - KAS_URL=http://kas:8000
      - NGINX_HOST=etheria.local
      - MONOLOG_LEVEL
    hostname: etheria.local
    image: nginx
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    volumes:
      - ./certs/ca.crt:/etc/nginx/ca-crt.pem
      - ./certs/reverse-proxy.crt:/etc/nginx/server-crt.pem
      - ./certs/reverse-proxy.key:/etc/nginx/server-key.pem
      - ./reverse-proxy/entrypoint.sh:/entrypoint.sh:cached
      - ./reverse-proxy/logs:/var/log/nginx:cached
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.template:cached
      - ./containers/python_base/tools:/tools:cached
  postgres:
    expose:
      - 5432
    image: postgres:12
    environment:
      - POSTGRES_USER=eas_user
      - POSTGRES_PASSWORD=eas_password
      - POSTGRES_DB=eas_db
