# TODO DEPRECATED - this should be dropped in favor of a Helm-based install and KUTTL test
version: "3.8"
volumes:
  key-store:
services:
  genkeys:
    entrypoint: /tools/wait-after /tools/genkeys-if-needed
    environment:
      - MONOLOG_LEVEL
      - EAS_UID=908
      - KAS_UID=909
      - CLIENT_UID=1909
    image: opentdf/tdf-python-base:${PY_VERSION:-3.9}
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - key-store:/certs/
    working_dir: /tools
  eas:
    depends_on:
      - genkeys
      - postgres
    environment:
      - EAS_ATTRIBUTES_JSON
      - EAS_DB_PATH=/eas_app/db/data/eas_database.sqlite
      - EAS_ENTITY_ID_HEADER=X-Forwarded-Entity-Id
      - EAS_USERS_JSON
      - FLASK_DEBUG=True
      - GUNICORN_WORKERS=1
      - JSON_LOGGER=False
      - KAS_DEFAULT_URL=https://etheria.local:4443/kas
      - LOGLEVEL=DEBUG
      - MONOLOG_LEVEL
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=eas_user
      - POSTGRES_PASSWORD=eas_password
      - POSTGRES_DB=eas_db
      - EAS_UID=908
    expose:
      - 4010
    build:
      args:
        - PY_VERSION=${PY_VERSION:-3.9}
      context: ./containers/eas
      dockerfile: Dockerfile
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - key-store:/certs/
  kas:
    build:
      args:
        - PY_VERSION=${PY_VERSION:-3.9}
      context: ./containers/kas
      dockerfile: Dockerfile
    command: ["/kas_app/scripts/entrypoint"]
    depends_on:
      - genkeys
    entrypoint: ["/tools/wait-for-file", "/certs/kas-ec.crt", "/certs/ca.crt", "/certs/bob_5678-ec.crt", "--"]
    environment:
      - EAS_HOST=https://etheria.local/eas/
      - FLASK_DEBUG=True
      - GUNICORN_WORKERS=1
      - JSON_LOGGER=False
      - CA_CERT_PATH=/certs/ca.crt
      - CLIENT_CERT_PATH=/certs/kas-ec.crt
      - CLIENT_KEY_PATH=/certs/kas-ec.key
      - LOGLEVEL=DEBUG
      - MONOLOG_LEVEL
      - KAS_UID=909
    expose:
      - 8000
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ./containers/python_base/tools:/tools
      - key-store:/certs/
  etheria.local:
    depends_on:
      - eas
    environment:
      - EAS_ENTITY_ID_HEADER=X-Forwarded-Entity-Id
      - EAS_URL=http://eas:4010
      - KAS_URL=http://kas:8000
      - NGINX_HOST=etheria.local
      - SET_PKI_MODE=on
      - MONOLOG_LEVEL
    entrypoint:
      [
        "/tools/wait-for-file",

        "--ln",
        "/certs/ca.crt",
        "/etc/nginx/ca-crt.pem",

        "--ln",
        "/certs/reverse-proxy.crt",
        "/etc/nginx/server-crt.pem",

        "--ln",
        "/certs/reverse-proxy.key",
        "/etc/nginx/server-key.pem",

        "--",

        "/entrypoint.sh",
      ]
    expose:
      - 443
      - 4443
    hostname: etheria.local
    image: nginx
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - ./reverse-proxy/entrypoint.sh:/entrypoint.sh:cached
      - ./reverse-proxy/logs:/var/log/nginx:cached
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.template:cached
      - ./containers/python_base/tools:/tools:cached
      - key-store:/certs/
  xtest-py-oss:
    build:
      args:
        - NODE_VERSION=${NODE_VERSION:-lts-buster}
        - PY_OSS_VERSION=${PY_OSS_VERSION:-==1.1.1}
      context: .
      dockerfile: xtest/Dockerfile
    command:
      [
        "/xtest/scripts/wait-and-test",
        "/xtest/config-oss.json",
        "--crud",
        "--owner",
        "CN=Alice_1234",
        "--stage",
        "compose",
        "--sdks",
        "sdk/py/oss/cli.sh",
      ]
    depends_on:
      - etheria.local
    entrypoint:
      [
        "/tools/wait-for-file",

        "--ln",
        "/certs/ca.crt",
        "/usr/local/share/ca-certificates/tdf3-ca.crt",

        "--ln",
        "/certs/Alice_1234.crt",
        "/xtest/Alice_1234.crt",
        "--ln",
        "/certs/Alice_1234.key",
        "/xtest/Alice_1234.key",

        "--ln",
        "/certs/bob_5678.crt",
        "/xtest/bob_5678.crt",
        "--ln",
        "/certs/bob_5678.key",
        "/xtest/bob_5678.key",

        "--",
      ]
    environment:
      - TDF3_CERT_AUTHORITY=/usr/local/share/ca-certificates/tdf3-ca.crt
      - MONOLOG_LEVEL
      - CLIENT_UID=1909
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - key-store:/certs/
  postgres:
    expose:
      - 5432
    image: postgres:12
    environment:
      - POSTGRES_USER=eas_user
      - POSTGRES_PASSWORD=eas_password
      - POSTGRES_DB=eas_db
