apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entitlement-store.fullname" . }}-cm
  labels:
    {{- include "entitlement-store.labels" . | nindent 4 }}
data:
  OIDC_AUTHORIZATION_URL: {{ ( include "entitlement-store.oidc.externalUrl" . ) }}/realms/{{ .Values.oidc.realm}}/protocol/openid-connect/auth
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | quote }}
  OIDC_CONFIGURATION_URL: {{ ( include "entitlement-store.oidc.internalUrl" . ) }}/realms/{{ .Values.oidc.realm}}/.well-known/openid-configuration
  OIDC_REALM: {{ .Values.oidc.realm | quote }}
  OIDC_SERVER_URL: {{ ( include "entitlement-store.oidc.internalUrl" . ) | quote }}
  OIDC_TOKEN_URL: {{ ( include "entitlement-store.oidc.externalUrl" . ) }}/realms/{{ .Values.oidc.realm}}/protocol/openid-connect/token
  OIDC_SCOPES: {{ .Values.oidc.scopes | quote }}
  OPENAPI_URL: {{ .Values.openapiUrl | quote }}
  POSTGRES_DATABASE: {{ coalesce .Values.postgres.database .Values.global.opentdf.common.postgres.database | quote }}
  POSTGRES_HOST: {{ coalesce .Values.postgres.host .Values.global.opentdf.common.postgres.host | quote }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  SERVER_LOG_LEVEL: {{ .Values.logLevel | quote }}
  SERVER_ROOT_PATH: {{ .Values.serverRootPath | quote }}
  SERVER_CORS_ORIGINS: {{ .Values.serverCorsOrigins | quote }}
