apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entitlement-store.name" . }}-cm
  labels:
    {{- include "entitlement-store.labels" . | nindent 4 }}
data:
  POSTGRES_DATABASE: {{ coalesce .Values.postgres.database .Values.global.opentdf.common.postgres.database | quote }}
  POSTGRES_HOST: {{ coalesce .Values.postgres.host .Values.global.opentdf.common.postgres.host | quote }}
  POSTGRES_SCHEMA: {{ .Values.postgres.schema | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  SERVER_LOG_LEVEL: {{ .Values.logLevel | quote }}
