global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: mydbapassword

abacus:
  attributes:
    serverUrl: https://opentdf.us/v2/attributes
  entitlements:
    serverUrl: https://opentdf.us/v2/entitlements
  oidc:
    serverUrl: https://keycloak.opentdf.us/auth/
    clientId: opentdf-us-abacus
    realm: opentdf-realm
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx

attributes:
  rootPath: /v2/attributes
  publicName: "Attributes"
  openapiPath: /openapi.json
  corsOrigins: "http://localhost:3000"
  logLevel: debug
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_attribute_manager
    password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
    database: tdf_database
    schema: tdf_attribute
  oidc:
    clientId: opentdf-us-attributes
    clientSecret:
    realm: opentdf-realm
    scopes: "profile"
    #    trailing / is required
    serverUrl: https://keycloak.opentdf.us/auth/
    configurationUrl: https://keycloak.opentdf.us/auth/realms/opentdf-realm/.well-known/openid-configuration
    authorizationUrl: https://keycloak.opentdf.us/auth/realms/opentdf-realm/protocol/openid-connect/auth
    tokenUrl: https://keycloak.opentdf.us/auth/realms/opentdf-realm/protocol/openid-connect/token
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /v2/attributes(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2

entitlements:
  rootPath: /v2/entitlements
  publicName: "Entitlements"
  openapiPath: /openapi.json
  corsOrigins: "http://localhost:3000"
  logLevel: debug
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_entitlement_manager
    password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
    database: tdf_database
    schema: tdf_entitlement
  oidc:
    clientId: opentdf-us-entitlements
    clientSecret:
    realm: opentdf-realm
    scopes: "profile"
    #    trailing / is required
    serverUrl: https://keycloak.opentdf.us/auth/
    configurationUrl: https://keycloak.opentdf.us/auth/realms/opentdf-realm/.well-known/openid-configuration
    authorizationUrl: https://keycloak.opentdf.us/auth/realms/opentdf-realm/protocol/openid-connect/auth
    tokenUrl: https://keycloak.opentdf.us/auth/realms/opentdf-realm/protocol/openid-connect/token
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /v2/entitlements(/|$)(.*)
            pathType: Prefix
      - host: keycloak.opentdf.us
        paths:
          - path: /v2/entitlements(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2

claims:
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_entitlement_reader
    password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
    database: tdf_database
    schema: tdf_entitlement

access:
  logLevel: DEBUG
  endpoints:
    easHost: http://opentdf-attributes:4020
    statsdHost: opentdf-statsd
    oidcPubkeyEndpoint: https://keycloak.opentdf.us
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /kas(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2