global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: mydbapassword

abacus:
  attributes:
    serverUrl: https://opentdf.us/v2/attributes
  oidc:
#    serverUrl: https://keycloak.opentdf.us/auth/
    serverUrl: https://etheria-pflynn.com/keycloak/auth/
    clientId: opentdf-us-abacus
    realm: tdf
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx

attributes:
  rootPath: /v2/attributes
  publicName: "Attributes"
  openapiPath: /openapi.json
  corsOrigins: "opentdf.us"
  logLevel: debug
  postgres:
    host: opentdf-postgresql
    port: 5432
    user: tdf_attribute_manager
    password: bXlQb3N0Z3Jlc1Bhc3N3b3Jk
    database: tdf_database
    schema: tdf_attribute
  oidc:
    clientId: opentdf-us-attributes
    clientSecret:
    realm: tdf
    #    trailing / is required
    serverUrl: https://etheria-pflynn.com/keycloak/auth/
    configurationUrl: https://etheria-pflynn.com/keycloak/auth/realms/tdf/.well-known/openid-configuration
    authorizationUrl: https://etheria-pflynn.com/keycloak/auth/realms/tdf/protocol/openid-connect/auth
    tokenUrl: https://etheria-pflynn.com/keycloak/auth/realms/tdf/protocol/openid-connect/token
  ingress:
    enabled: true
    hosts:
      - host: opentdf.us
        paths:
          - path: /v2/attributes(/|$)(.*)
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
