services:
  ghcr-registry:
    url: https://ghcr.io
    type: oci
    credentials:
      bearer:
        token: "${CR_PAT}"

bundles:
  entitlement-policy:
    service: ghcr-registry
    resource: ghcr.io/opentdf/entitlement-pdp/entitlements-policybundle:main
    # Set `persist` to true so OPA will expect/check for a local policy cache
    persist: true
    # On startup, if persistence is enabled, $PERSIST_DIR/bundles/bundle.tar.gz
    # will be loaded. However OPA will keep trying to update it. Setting `trigger`
    # to manual means we disable bundle update polling entirely
    trigger: "manual"
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120


# Sets the persistence directory. Policy deployment for airgapped installs
# can be achieved by putting a valid `bundle.tar.gz` under a `/bundles`
# subfolder in this dir - OPA will load the local cache, and carry on.
persistence_directory: derp-opa

distributed_tracing:
  type: grpc
  address: opentelemetry-collector.otel.svc:4317
  service_name: entitlement-pdp-opa
  sample_percentage: 50
  encryption: "off"

decision_logs:
  console: true
