services:
  policy-registry:
    url: https://ghcr.io
    type: oci
    credentials:
      bearer:
        token: "${CR_PAT}"
bundles:
  entitlement-policy:
    service: policy-registry
    resource: ghcr.io/opentdf/entitlement-pdp/entitlements-policybundle:main
    trigger: "manual"
    persist: true
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 60
persistence_directory: ./policy-cache/
decision_logs:
  console: true
