# https://www.openpolicyagent.org/docs/latest/
services:
  policy-registry:
    url: https://ghcr.io
    type: oci

bundles:
  entitlement-policy:
    service: policy-registry
    resource: ghcr.io/opentdf/entitlement-pdp/entitlements-policybundle:main
    trigger: periodic
    persist: false
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 60
persistence_directory: ./policy-cache/
decision_logs:
  console: true
