# OpenAPI Spec https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md
openapi: 3.0.0
info:
  version: 1.0.0
  title: Attribute Provider
  termsOfService: https://www.virtru.com/terms-of-service/
  contact:
    email: support@virtru.com
  license:
    name: MIT
    url: https://github.com/opentdf/backend/blob/master/LICENSE

externalDocs:
  description: Developer Hub
  url: https://developer.virtru.com/

paths:
  "/":
    post:
      summary: This is the POST received from Virtru's Keycloak Protocol Mapper
      description: |
        This is the POST received from Virtru's Keycloak Protocol Mapper.
        For more information, see: FIXME
      operationId: attribute_provider.app.post_from_keycloak_protocol_mapper_impl
      requestBody:
        $ref: "#/components/requestBodies/ProtocolMapperRequest"
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: "0.0.0"
        "400":
          $ref: "#/components/responses/BadRequest"

components:
  responses:
    ### Errors
    BadRequest:
      description: 400 Bad request
      content:
        application/json:
          schema:
            properties:
              detail:
                type: string
              status:
                type: number
                default: 400
              title:
                type: string
                default: Bad request
              type:
                type: string
                default: about:blank

  requestBodies:
    ProtocolMapperRequest:
      description: Request from Virtru Keycloak Protocol Mapper
      required: true
      content:
        application/json:
          schema:
            oneOf:
            - type: object
              required:
                - client_id
                - claim_request_type
                - client_pk
                - token
              maxProperties: 5
              properties:
                client_id:
                  type: string
                claim_request_type:
                  type: string
                client_pk:
                  type: string
                  format: base64
                token:
                  type: object
                username:
                  type: string
