apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storage.name" . }}-cm
  labels:
    {{- include "storage.labels" . | nindent 4 }}
data:
  AWS_DEFAULT_REGION: {{ .Values.s3BucketRegion | quote }}
  BUCKET: {{ .Values.s3Bucket | quote }}
  CORS_ORIGINS: {{ .Values.corsOrigins | quote }}
  SERVER_LOG_LEVEL: {{ .Values.logLevel | quote }}
