eas:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: eas-dryrun.virtrunetes.com
      paths:
      - /
    tls:
    - hosts:
      - eas-dryrun.virtrunetes.com
      secretName: eas-tls
  endpoints:
    kasDefaultUrl: https://access-dryrun.virtrunetes.com

access:
  replicaCount: 1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    enabled: true
    hosts:
    - host: access-dryrun.virtrunetes.com
      paths:
      - /
    tls:
    - hosts:
      - access-dryrun.virtrunetes.com
      secretName: access-tls
  endpoints:
    easHost: https://eas-dryrun.virtrunetes.com

attribute-provider:
  image:
    name: virtru/tdf-claim-test-webservice:0.1.1
  port: 5000

keycloak-bootstrap:
  image:
    name: virtru/tdf-keycloak-bootstrap:0.2.1
    pullPolicy: Always

attributes:
  image:
    name: virtru/tdf-attributes-service

entitlements:
  image:
    name: virtru/tdf-entitlements-service

tdf-storage:
  image:
    name: virtru/tdf-storage-service
