{{- if .Values.embedded.keycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" .Subcharts.keycloak }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.global.opentdf.common.keycloak.user }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.opentdf.common.keycloak.password}}
  KC_HOSTNAME: {{ ( include "backend.keycloak.externalHostname" . ) | quote }}
  KC_HOSTNAME_ADMIN: {{ ( include "backend.keycloak.externalHostname" . ) | quote }}
  KC_DB_USERNAME: "keycloak_manager"
  KC_DB_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  KC_DB_URL_HOST: {{ .Values.global.opentdf.common.postgres.host }}
  KC_DB_URL_DATABASE: {{ .Values.keycloak.externalDatabase.database }}
{{- end }}
---
{{- if .Values.embedded.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.primary.fullname" .Subcharts.postgresql }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.secrets.postgres.dbPassword }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attributes.fullname" .Subcharts.attributes }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
{{- if .Values.bootstrapKeycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Subcharts "keycloak-bootstrap" | include "keycloak-bootstrap.fullname" }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  CLIENT_SECRET: {{ .Values.secrets.keycloakBootstrap.clientSecret }}
  keycloak_admin_username: {{ .Values.global.opentdf.common.keycloak.user }}
  keycloak_admin_password: {{ .Values.global.opentdf.common.keycloak.password }}
  ATTRIBUTES_USERNAME: {{ .Values.secrets.keycloakBootstrap.attributes.username }}
  ATTRIBUTES_PASSWORD: {{ .Values.secrets.keycloakBootstrap.attributes.password }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Subcharts "entitlement-store" | include "entitlement-store.fullname" }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Subcharts "entitlement-pdp" | include "entitlement-pdp.fullname" }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  opaPolicyPullSecret: {{ .Values.secrets.opaPolicyPullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Subcharts "entitlements" | include "entitlements.fullname" }}-otdf-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "backend.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}

