apiVersion: v1
kind: Secret
metadata:
  name: opentdf-keycloak-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.postgres.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  KEYCLOAK_USER: {{ .Values.secrets.keycloak.user }}
  KEYCLOAK_PASSWORD: {{ .Values.secrets.keycloak.password}}
  KEYCLOAK_FRONTEND_URL: {{ ( include "backend.keycloak.externalUrl" . ) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opentdf-postgres-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
type: Opaque
stringData:
  postgresql-password: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: attributes-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-bootstrap-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: entitlement-store-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opentdf-entitlement-pdp-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  opaPolicyPullSecret: {{ .Values.secrets.opaPolicyPullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: entitlements-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
{{- if not .Values.secrets.kas.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kas.secretRef.name }}
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
type: Opaque
data:
  ATTR_AUTHORITY_CERTIFICATE: |-
        {{ ( include "backend.kas.ATTR_AUTHORITY_CERTIFICATE" . ) }}
  KAS_EC_SECP256R1_CERTIFICATE: |-
        {{ ( include "backend.kas.KAS_EC_SECP256R1_CERTIFICATE" . ) }}
  KAS_CERTIFICATE: |-
        {{ ( include "backend.kas.KAS_CERTIFICATE" . ) }}
  KAS_EC_SECP256R1_PRIVATE_KEY: |-
        {{ ( include "backend.kas.KAS_EC_SECP256R1_PRIVATE_KEY" . ) }}
  KAS_PRIVATE_KEY: |-
        {{ ( include "backend.kas.KAS_PRIVATE_KEY" . ) }}
{{- end }}     
