apiVersion: v1
kind: Secret
metadata:
  name: opentdf-keycloak-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.global.opentdf.common.keycloak.user }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.opentdf.common.keycloak.password}}
  KC_HOSTNAME: {{ ( include "backend.keycloak.externalUrl" . ) | quote }}
  KC_HOSTNAME_ADMIN: {{ ( include "backend.keycloak.externalUrl" . ) | quote }}
  KC_DB_USERNAME: "keycloak_manager"
  KC_DB_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  KC_DB_URL_HOST: {{ .Values.keycloakx.externalDatabase.host }}
  KC_DB_URL_DATABASE: {{ .Values.keycloakx.externalDatabase.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-bootstrap-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  keycloak_admin_username: {{ .Values.global.opentdf.common.keycloak.user }}
  keycloak_admin_password: {{ .Values.global.opentdf.common.keycloak.password }}
  CLIENT_SECRET: {{ .Values.secrets.keycloakBootstrap.keycloak.clientSecret }}
  ATTRIBUTES_USERNAME: {{ .Values.secrets.keycloakBootstrap.attributes.username }}
  ATTRIBUTES_PASSWORD: {{ .Values.secrets.keycloakBootstrap.attributes.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opentdf-postgres-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}    
type: Opaque
stringData:
  postgresql-password: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: attributes-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-bootstrap-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: entitlement-store-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opentdf-entitlement-pdp-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  opaPolicyPullSecret: {{ .Values.secrets.opaPolicyPullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: entitlements-secrets
  labels:
    app: {{ .Values.name }}
    chart: {{ template "backend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}

