apiVersion: v1
kind: Secret
metadata:
  name: opentdf-keycloak-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.postgres.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  KEYCLOAK_USER: {{ .Values.secrets.keycloak.user }}
  KEYCLOAK_PASSWORD: {{ .Values.secrets.keycloak.password}}
---
 apiVersion: v1
kind: Secret
metadata:
  name: opentdf-postgres-secret
type: Opaque
stringData:
  postgresql-password: {{ .Values.secrets.postgres.dbPassword }}
 