apiVersion: v1
kind: Secret
metadata:
  name: opentdf-keycloak-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.postgres.dbUser }}
  DB_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  KEYCLOAK_USER: {{ .Values.secrets.keycloak.user }}
  KEYCLOAK_PASSWORD: {{ .Values.secrets.keycloak.password}}
  KEYCLOAK_FRONTEND_URL: {{ ( include "backend.keycloak.externalUrl" . ) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opentdf-postgres-secret
type: Opaque
stringData:
  postgresql-password: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: attributes-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-bootstrap-secrets
type: Opaque
stringData:
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: entitlement-store-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opentdf-entitlement-pdp-secret
type: Opaque
stringData:
  opaPolicyPullSecret: {{ .Values.secrets.opaPolicyPullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: entitlements-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret }}

