kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
  labels:
    type: local
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/tdf3/eas/sqlite
