{{- if .Values.createPolicySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "entitlementpdp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  opaPolicyPullSecret: {{ .Values.secret.opaPolicyPullSecret | b64enc }}
{{- end }}
