apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  ports:
  - port: {{ .Values.config.listenPort }}
    name: {{ .Values.name }}
    appProtocol: http
    targetPort: {{ .Values.config.listenPort }}
  selector:
    app: {{ .Values.name }}
