apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
  labels:
    app: {{ .Values.name }}
    chart: {{ template "entitlementpdp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        env:
          - name: LISTEN_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: listenPort
          - name: EXTERNAL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: externalHost
          - name: VERBOSE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: verbose
          - name: DISABLE_TRACING
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: disableTracing
          - name: OTLP_COLLECTOR_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: otlpCollectorEndpoint
          - name: OPA_CONFIG_PATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.name }}-config
                key: opaConfigPath
          - name: OPA_POLICYBUNDLE_PULLCRED
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-secret
                key: opaPolicyPullSecret
        ports:
          - containerPort: {{ .Values.config.listenPort }}
        volumeMounts:
          - name: opa-config
            mountPath: {{ .Values.opaConfigMountPath }}
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.config.listenPort }}
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.config.listenPort }}
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.config.listenPort }}
          failureThreshold: 30
          periodSeconds: 10
      volumes:
        - name: opa-config
          configMap:
            name: {{ .Values.name }}-config
            # An array of keys from the ConfigMap to create as files
            items:
            - key: "opa-config.yaml"
              path: "opa-config.yaml"
      {{- with .Values.global.opentdf.common.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
