{{- if .Values.createPolicySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entitlement-pdp.fullname" . }}-secret
  labels:
    {{- include "entitlement-pdp.labels" . | nindent 4 }}
type: Opaque
data:
  opaPolicyPullSecret: {{ .Values.secret.opaPolicyPullSecret | b64enc }}
{{- end }}
