{{- if .Values.createPolicySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entitlement-pdp.fullname" . }}-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "entitlement-pdp.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  opaPolicyPullSecret: {{ .Values.secret.opaPolicyPullSecret | b64enc }}
{{- end }}
