apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "entity-resolution.fullname" . }}-cm
  labels:
    {{- include "entity-resolution.labels" . | nindent 4 }}
data:
  listenPort: {{ .Values.config.listenPort | quote }}
  externalHost: {{ .Values.config.externalHost | quote }}
  verbose: {{ .Values.config.verbose | quote }}
  disableTracing: {{ .Values.config.disableTracing | quote }}
  otlpCollectorEndpoint: {{ .Values.config.otlpCollectorEndpoint | quote }}
  keycloakUrl: {{ ( include "entity-resolution.keycloakUrl" . ) | quote }}
  keycloakRealm: {{ .Values.config.keycloak.realm | quote }}
  keycloakClientId: {{ .Values.config.keycloak.clientId | quote }}
  keycloakLegacy: {{ .Values.config.keycloak.legacy | quote }}
