apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: {{ template "entityresolution.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.config.listenPort }}
    name: {{ .Values.name }}
    appProtocol: http
    targetPort: {{ .Values.config.listenPort }}
  selector:
    app: {{ .Values.name }}
