{{- if .Values.createKeycloakClientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-keycloak-client-secret
  labels:
    app: {{ .Values.name }}
    chart: {{ template "entityresolution.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  keycloakClientSecret: {{ .Values.secret.keycloak.clientSecret | b64enc }}
{{- end }}
---
{{- if .Values.useImagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
