{{- if .Values.createKeycloakClientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entity-resolution.fullname" . }}-keycloak-client-secret
  labels:
    {{- include "entity-resolution.labels" . | nindent 4 }}
type: Opaque
data:
  keycloakClientSecret: {{ .Values.secret.keycloak.clientSecret | b64enc }}
{{- end }}
---
{{- if .Values.useImagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entity-resolution.fullname" . }}-pull-secret
  labels:
    {{- include "entity-resolution.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "entity-resolution.imagePullSecret" . }}
{{- end }}
