{{- if .Values.createKeycloakClientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entity-resolution.fullname" . }}-keycloak-client-secret
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "entity-resolution.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  keycloakClientSecret: {{ .Values.secret.keycloak.clientSecret | b64enc }}
{{- end }}
---
{{- if .Values.useImagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "entity-resolution.fullname" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . }}
{{- end }}
