apiVersion: v1
kind: Service
metadata:
  name: {{ include "entity-resolution.fullname" . }}
  labels:
    {{- include "entity-resolution.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.config.serverPort }}
    name: {{ include "entity-resolution.fullname" . }}
    appProtocol: http
    targetPort: {{ .Values.config.serverPort }}
  selector:
    {{- include "entity-resolution.selectorLabels" . | nindent 4 }}
