apiVersion: v1
kind: Service
metadata:
  name: {{ include "entity-resolution.fullname" . }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ include "entity-resolution.chart" . | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.config.listenPort }}
    name: include "entity-resolution.fullname"
    appProtocol: http
    targetPort: {{ .Values.config.listenPort }}
  selector:
    app: {{ .Chart.Name | quote }}
