package handlers

import (
	"fmt"
	"net/http"

	_ "github.com/opentdf/v2/entitlement-pdp/docs" // docs is generated by Swag CLI, you have to import it.
	httpSwagger "github.com/swaggo/http-swagger"   // http-swagger middleware
)

type Swagger struct {
	Address string
}

func (s Swagger) ServeHTTP(_ http.ResponseWriter, _ *http.Request) {
	httpSwagger.URL(fmt.Sprintf("http://%s/docs/doc.json", s.Address)) // The url pointing to API definition
}
