"""add group by

Revision ID: f17c4bf35497
Revises: cd386fbea691
Create Date: 2022-07-01 10:49:02.901919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17c4bf35497'
down_revision = 'cd386fbea691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('rule', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('values_array', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('group_by_attr', sa.Integer(), nullable=True),
    sa.Column('group_by_attrval', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group_by_attr'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['attribute_namespace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
