"""add group by

Revision ID: c6d5f2780578
Revises: fcb089ad4e51
Create Date: 2022-06-30 11:04:57.564584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d5f2780578'
down_revision = 'fcb089ad4e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('rule', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('values_array', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('group_by_attr', sa.Integer(), nullable=True),
    sa.Column('group_by_attrval', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['group_by_attr'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['attribute_namespace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute')
    op.drop_table('attribute_namespace')
    # ### end Alembic commands ###
