{{- if not .Values.externalEnvSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "kas.secretName" . ) }}
  labels:
    app.kubernetes.io/name: {{ (include "kas.secretName" . ) }}
    helm.sh/chart: {{ include "kas.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kas  
type: Opaque
data:
  ATTR_AUTHORITY_CERTIFICATE: |-
        {{ ( include "kas.ATTR_AUTHORITY_CERTIFICATE" . ) }}
  KAS_EC_SECP256R1_CERTIFICATE: |-
        {{ ( include "kas.KAS_EC_SECP256R1_CERTIFICATE" . ) }}
  KAS_CERTIFICATE: |-
        {{ ( include "kas.KAS_CERTIFICATE" . ) }}
  KAS_EC_SECP256R1_PRIVATE_KEY: |-
        {{ ( include "kas.KAS_EC_SECP256R1_PRIVATE_KEY" . ) }}
  KAS_PRIVATE_KEY: |-
        {{ ( include "kas.KAS_PRIVATE_KEY" . ) }}
{{- end }}  