apiVersion: v2
name: claims
version: 0.0.1
description: Provides 'claims' objects as the backend for an OpenTDF authZ service
type: application
maintainers:
  - name: Virtru
icon: https://avatars.githubusercontent.com/u/90051847?s=200&v=4
appVersion: "main"
