# Global values that may be overridden by a parent chart.
global:
  opentdf:
    common:
      # JSON passed to the deployment's template.spec.imagePullSecrets
      imagePullSecrets: []
      postgres:
        # postgres server's k8s name or global DNS for external server
        host: postgresql
        # postgres server port
        port: 5432
        # The database name within the given server
        database: tdf_database

# Sets the default loglevel for the application. One of the valid python logging
# levels: `DEBUG, INFO, WARNING, ERROR, CRITICAL`
logLevel: INFO

# Sets the default number of pod replicas in the deployment.
# Ignored if autoscaling.enabled == true
replicaCount: 1

# Name of application. Used during oauth flows, for example when connecting to
# the OpenAPI endpoint with an OAuth authentication
serverPublicName: "entitlement-store"


# Configure the container image to use in the deployment.
image:
  # Override for global.opentdf.common.oidcInternalBaseUrl & url path
  internalHost:
  # Override for global.opentdf.common.oidcExternalBaseUrl & url path
  externalHost:
  # The image selector, also called the 'image name' in k8s documentation
  # and 'image repository' in docker's guides.
  repo: ghcr.io/opentdf/entitlement_store
  # Chart.AppVersion will be used for image tag, override here if needed
  # tag: main
  # The container's `imagePullPolicy`
  pullPolicy: IfNotPresent

# JSON passed to the deployment's template.spec.imagePullSecrets.
# Overrides global.opentdf.common.imagePullSecrets
imagePullSecrets:

# Select a specific name for the resource, instead of the default, entitlement-store
nameOverride: ""

# The fully qualified appname override
fullnameOverride: ""

# A service account to create
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: null

# Values for the deployment spec.template.metadata.annotations field
podAnnotations: {}

# Values for deployment's spec.template.spec.securityContext
podSecurityContext: {}

# Values for deployment's spec.template.spec.containers.securityContext
securityContext: {}

# JSON to locate a k8s secret containing environment variables.
# Notably, this file should include the following environemnt variable definitions:
#     POSTGRES_PASSWORD: Password corresponding to postgres.user below
#     KAS_CERTIFICATE: Public key for Key Access service
#     KAS_EC_SECP256R1_CERTIFICATE: Public key (EC Mode) for Key Access service
secretRef: |-
  name: {{ template "entitlement-store.fullname" . }}-secret

# Service configuation information.
service:
  # Service `spec.type`
  type: ClusterIP
  # Port to assign to the `http` port
  port: 5000

# Specify required limits for deploying this service to a pod.
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube.
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Configuration for the database backend
postgres:
  # Must be a postgres user with tdf_entitlement_reader role
  user: tdf_entitlement_reader
  # The entitlement schema
  schema: tdf_entitlement
  # Override for global.opentdf.common.postgres.host
  host:
  # Override for global.opentdf.common.postgres.post
  port:
  # Override for global.opentdf.common.postgres.database
  database:
