name: 'opentdf-entitlement-pdp'
replicaCount: 3
image:
  repo: ghcr.io/opentdf/entitlement-pdp
  # tag: 0.0.5
  pullPolicy: IfNotPresent

useImagePullSecret: false
# imageCredentials:
#   registry: ghcr.io
#   username: username
#   password: password
#   email: nope@nah.com

secret:
  opaPolicyPullSecret: "YOUR_GHCR_PAT_HERE"

opaConfigMountPath: "/etc/opa/config"

opaConfig:
  policy:
    # If `useStaticPolicy` is set to `true`, then an OPA config will be generated
    # that forces the use of a policy bundle that was built and packed into the `entitlement-pdp`
    # container at *build* time, and no policy bundle will be fetched dynamically from the registry
    # on startup.
    # This is not a desirable default, but it is useful in offline deployments.
    useStaticPolicy: false
    OCIRegistryUrl: "https://ghcr.io"
    bundleRepo: "ghcr.io/opentdf/entitlement-pdp/entitlements-policybundle"
    # `bundleTag` will default to `.Chart.AppVersion` if unset
    # bundleTag: 0.0.6

    # This will tell OPA to ignore TLS errors (bad cert, self-signed cert, etc)
    # when downloading an OCI policy bundle from an OCI registry.
    #
    # Unsuitable for production, used for testing with `localhost` registries
    allowInsecureTLS: false
    updatePolling:
      minDelay: 60
      maxDelay: 120
  extraConfigYaml:
  # Any extra/additional OPA config defined here will be appended as-is,
  # as raw YAML to the OPA config file generated by the chart.
    decision_logs:
      console: true
    # distributed_tracing:
    #   type: grpc
    #   address: opentelemetry-collector.otel.svc:4317
    #   service_name: entitlement-pdp-opa
    #   sample_percentage: 50
    #   encryption: "off"


config:
  listenPort: 3355
  externalHost: ""
  verbose: "false"
  disableTracing: "false"
  otlpCollectorEndpoint: "opentelemetry-collector.otel.svc:4317"
  opaConfigPath: "/etc/opa/config/opa-config.yaml"
