# act --container-architecture linux/amd64 --workflows .github/workflows/analyze.yaml
name: analyze
on:
  push:
permissions:
  contents: read
jobs:
  # https://github.com/ChartBoost/ruff-action
  python-lint:
    name: python-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./containers/kas/kas_core"
  # https://github.com/golangci/golangci-lint-action
  go-lint:
    name: go-lint
    strategy:
      matrix:
        go: ['1.21','1.20','1.19']
#        bug in goimports on windows-latest
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: containers/entitlement-pdp
