name: build
on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Build Backend"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      imageTag:
        description: image tag
        type: string
        default: main
        required: false
  
jobs:
  set-image-tag:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'workflow_dispatch'
        run: |-
          echo "Running with Image Tag: ${{ inputs.imageTag }}"
          echo "image_tag=${{ github.events.inputs.imageTag }}" >> $GITHUB_ENV
      - if: github.event_name != 'workflow_dispatch'
        run: |-
          echo "Running with Image Tag: main"
          echo "image_tag=main" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.image_tag }}" # This will output 'main'
    outputs:
      image_tag: ${{ env.image_tag }}

  attributes:
    needs: set-image-tag
    runs-on: ubuntu-20.04
    steps:
      - name: Echo image tag
        run: |-
          echo "Running with Image Tag: ${{needs.set-image-tag.outputs.image_tag}}"
      - name: Attributes Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/opentdf/attributes:${{needs.set-image-tag.outputs.image_tag}}
          format: 'sarif'
          output: 'attributes-trivy-results.sarif'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: attributes-trivy-results.sarif
          path: attributes-trivy-results.sarif
          retention-days: 5

  printImageTagAfterSet:
    needs: set-image-tag
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{needs.set-image-tag.outputs.image_tag}}" # This will output 'main'
