name: build
on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Build Backend"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      imageTag:
        description: image tag
        type: string
        default: main
  
jobs:
  attributes:
    name: Attributes
    runs-on: ubuntu-20.04
    steps:
      - name: Echo image tag
        run: |-
          echo "Running with Image Tag: ${{ github.events.inputs.imageTag }}'" 
      # - name: Attributes Scan
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: ghcr.io/opentdf/attributes:${{ github.events.inputs.imageTag }}'
      #     format: 'sarif'
      #     output: 'attributes-trivy-results.sarif'
