name: deploy-production
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'  
        default: 'the tags are cool'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    name: deploy production
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
