name: Helm Lint

on: pull_request

jobs:
  helm-lint-test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/helmpack/chart-testing:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint
        run: |
          ct lint --target-branch main --all charts/

      - name: Render Templates
        run: |
          cd charts
          for d in */ ; do
              if [ -f "$d/Chart.yaml" ]; then
                echo "Rendering Helm chart $d to validate defaults..."
                helm template "$d"
              fi
          done
