
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  cosign-signing-workflow:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
        with:
          cosign-release: 'v1.11.1'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Write signing key to disk
        run: 'echo "$COSIGN_PRIVATE_KEY" > cosign.key'
        shell: bash
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
#        run: cosign sign --key cosign.key ghcr.io/opentdf/"${{ inputs.target }}:${{ inputs.version }}
        run: echo ghcr.io/opentdf/${{ inputs.target }}:${{ inputs.version }}
