
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      COSIGN_PASSWORD:
        required: true
      COSIGN_PUBLIC_KEY:
        required: true
jobs:
  signing-artifacts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/labeler@v4
      - name: Install cosign
        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
        with:
          cosign-release: 'v1.11.1'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Write signing key to disk
        run: 'echo "$COSIGN_PUBLIC_KEY" > cosign.key'
        shell: bash
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      - name: Verifying published artifacts
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign verify --key cosign.key ghcr.io/opentdf/entitlement_store:main
