
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      repo-token:
        required: true
      cosign_pass:
        required: true
      cosign_pub_key:
        required: true
jobs:
  signing-artifacts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/labeler@v4
        with:
          package: ${{ inputs.package }}
          tag: ${{ inputs.tag }}
      - name: Install cosign
        uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
        with:
          cosign-release: 'v1.11.1'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.repo-token }}
      - name: Write signing key to disk
        run: 'echo "$COSIGN_PUBLIC_KEY" > cosign.key'
        shell: bash
        env:
          COSIGN_PASSWORD: ${{ secrets.cosign_pass }}
          COSIGN_PUBLIC_KEY: ${{ secrets.cosign_pub_key }}
      - name: Verifying published artifacts
        env:
          COSIGN_PASSWORD: ${{ secrets.cosign_pass }}
        run: cosign verify --key cosign.key ${{ inputs.package }}:${{ inputs.tag }}
