name: Tagging

on:
  push:
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - entitlement_store
          - attributes
          - entitlements
          # what else??
          # - kas
          # - keycloak-bootstrap 
          # - entitlement-pdp
          # - entity-resolution
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/opentdf/${{ matrix.repo }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |-
            CONTAINER_REGISTRY=ghcr.io
          context: ./containers/${{ matrix.repo }}
          platforms: ${{ env.CONTAINER_ARCHS }}
          push: true
          # commenting out for testing
          # push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'opentdf/backend' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}