name: xtest
on:
  repository_dispatch:
    types: [xtest]
  workflow_dispatch:
jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://npm.pkg.github.com
      - name: config ghpr with pat
        run: |-
          cd tests/containers/clients
          echo @opentdf:registry=https://npm.pkg.github.com >.npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.READ_PACKAGES_PAT }} >>.npmrc
      - name: update packages
        run: |-
          echo "127.0.0.1 keycloak-http" | sudo tee -a /etc/hosts
          cd tests/containers/clients
          npm uninstall @opentdf/cli @opentdf/client
          npm uninstall @opentdf/cli
          npm install @opentdf/cli@${{ github.event.client_payload.version }}
          ls -l node_modules
          npm install
          ls -l node_modules
      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            helm
            tilt
          # This should be in sync with the minikube-deployed kube version below
          kubectl: "1.24.1"
          helm: "3.9.1"
          tilt: "0.30.4"
      - run: |
          kubectl version --client
          kustomize version
          tilt version
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 1.26.0
          # This should be in sync with the setup-tools version above
          kubernetes-version: 1.24.1
      - name: tilt-ci
        run: |-
          kubectl version
          # Tilt CI will fail to deploy with with complex helm charts
          # if any service crashes even once, irrespetive of Kube
          # backoff limits or scheduling logic.
          #
          # It does this because it generally does not play nice with Helm,
          # and imposes strict non-normative service dependencies on a system
          # that explicitly does not have those in the way tilt wants to have them.
          tilt ci -f Tiltfile.helm || true
          # So, we let it install the Helm chart, ignore it's misreporting of failures,
          # and wait for health ourselves in the test Tiltfile (from the k8s control plane, not tilt)
          tilt ci -f Tiltfile.xtest integration-test pki-test
